import { Market } from './types';

export const CATEGORIES = [
  'Todos',
  'Trending',
  'Breaking',
  'Novo',
  'Angola',
  'Política',
  'Economia',
  'Petróleo',
  'Crypto',
  'Desporto',
  'Finanças',
  'Geopolítica',
  'Tech',
  'Cultura',
  'Clima',
  'Eleições',
];

export const MOCK_MARKETS: Market[] = [
  {
    id: 'm1',
    question: 'Qual será o valor do dólar (USD/KZ) até o final do mês?',
    category: 'Finanças',
    image_url: 'https://picsum.photos/seed/usd-kz/400/200',
    volume: 1500000,
    end_date: '2026-03-31T23:59:59Z',
    yes_price: 0,
    no_price: 0,
    pool_yes: 0,
    pool_no: 0,
    is_multi: true,
    outcomes: [
      { id: '1', name: 'Abaixo de 850', price: 0.15, pool: 15000 },
      { id: '2', name: '850 – 900', price: 0.32, pool: 32000 },
      { id: '3', name: '900 – 950', price: 0.38, pool: 38000 },
      { id: '4', name: 'Acima de 950', price: 0.15, pool: 15000 }
    ],
    tags: ['Finanças', 'Dólar', 'Angola', 'Trending'],
  },
  {
    id: 'm2',
    question: 'Quanto o petróleo Brent atingirá este mês?',
    category: 'Finanças',
    image_url: 'https://picsum.photos/seed/brent/400/200',
    volume: 1200000,
    end_date: '2026-03-31T23:59:59Z',
    yes_price: 0,
    no_price: 0,
    pool_yes: 0,
    pool_no: 0,
    is_multi: true,
    outcomes: [
      { id: '1', name: 'Abaixo de $70', price: 0.20, pool: 20000 },
      { id: '2', name: '$70 – $80', price: 0.35, pool: 35000 },
      { id: '3', name: '$80 – $90', price: 0.30, pool: 30000 },
      { id: '4', name: 'Acima de $90', price: 0.15, pool: 15000 }
    ],
    tags: ['Finanças', 'Petróleo', 'Global'],
  },
  {
    id: 'm3',
    question: 'Qual preço o Bitcoin atingirá primeiro?',
    category: 'Crypto',
    image_url: 'https://picsum.photos/seed/btc-target/400/200',
    volume: 2500000,
    end_date: '2026-04-30T23:59:59Z',
    yes_price: 0,
    no_price: 0,
    pool_yes: 0,
    pool_no: 0,
    is_multi: true,
    outcomes: [
      { id: '1', name: '$60.000', price: 0.18, pool: 18000 },
      { id: '2', name: '$70.000', price: 0.27, pool: 27000 },
      { id: '3', name: '$80.000', price: 0.34, pool: 34000 },
      { id: '4', name: '$90.000', price: 0.21, pool: 21000 }
    ],
    tags: ['Crypto', 'Bitcoin', 'Trending'],
  },
  {
    id: 'm4',
    question: 'Qual criptomoeda terá maior crescimento este mês?',
    category: 'Crypto',
    image_url: 'https://picsum.photos/seed/crypto-growth/400/200',
    volume: 1800000,
    end_date: '2026-03-31T23:59:59Z',
    yes_price: 0,
    no_price: 0,
    pool_yes: 0,
    pool_no: 0,
    is_multi: true,
    outcomes: [
      { id: '1', name: 'Bitcoin', price: 0.25, pool: 25000 },
      { id: '2', name: 'Ethereum', price: 0.30, pool: 30000 },
      { id: '3', name: 'Solana', price: 0.28, pool: 28000 },
      { id: '4', name: 'Outras', price: 0.17, pool: 17000 }
    ],
    tags: ['Crypto', 'Altcoins', 'Trending'],
  },
  {
    id: 'm5',
    question: 'Qual setor crescerá mais em Angola este ano?',
    category: 'Angola',
    image_url: 'https://picsum.photos/seed/angola-sectors/400/200',
    volume: 900000,
    end_date: '2026-12-31T23:59:59Z',
    yes_price: 0,
    no_price: 0,
    pool_yes: 0,
    pool_no: 0,
    is_multi: true,
    outcomes: [
      { id: '1', name: 'Petróleo', price: 0.35, pool: 35000 },
      { id: '2', name: 'Tecnologia', price: 0.22, pool: 22000 },
      { id: '3', name: 'Construção', price: 0.18, pool: 18000 },
      { id: '4', name: 'Agricultura', price: 0.25, pool: 25000 }
    ],
    tags: ['Angola', 'Economia', 'Desenvolvimento'],
  },
  {
    id: 'm6',
    question: 'Qual será o maior problema económico este mês?',
    category: 'Angola',
    image_url: 'https://picsum.photos/seed/angola-economy/400/200',
    volume: 1100000,
    end_date: '2026-03-31T23:59:59Z',
    yes_price: 0,
    no_price: 0,
    pool_yes: 0,
    pool_no: 0,
    is_multi: true,
    outcomes: [
      { id: '1', name: 'Inflação', price: 0.40, pool: 40000 },
      { id: '2', name: 'Desemprego', price: 0.28, pool: 28000 },
      { id: '3', name: 'Câmbio', price: 0.22, pool: 22000 },
      { id: '4', name: 'Dívida', price: 0.10, pool: 10000 }
    ],
    tags: ['Angola', 'Economia', 'Sociedade'],
  },
  {
    id: 'm7',
    question: 'Qual será o resultado do próximo jogo de Angola?',
    category: 'Desporto',
    image_url: 'https://picsum.photos/seed/angola-match/400/200',
    volume: 800000,
    end_date: '2026-03-25T23:59:59Z',
    yes_price: 0,
    no_price: 0,
    pool_yes: 0,
    pool_no: 0,
    is_multi: true,
    outcomes: [
      { id: '1', name: 'Vitória', price: 0.42, pool: 42000 },
      { id: '2', name: 'Empate', price: 0.33, pool: 33000 },
      { id: '3', name: 'Derrota', price: 0.25, pool: 25000 }
    ],
    tags: ['Angola', 'Desporto', 'Futebol'],
  },
  {
    id: 'm8',
    question: 'Quem será o melhor jogador do campeonato?',
    category: 'Desporto',
    image_url: 'https://picsum.photos/seed/best-player/400/200',
    volume: 600000,
    end_date: '2026-05-31T23:59:59Z',
    yes_price: 0,
    no_price: 0,
    pool_yes: 0,
    pool_no: 0,
    is_multi: true,
    outcomes: [
      { id: '1', name: 'Jogador A', price: 0.30, pool: 30000 },
      { id: '2', name: 'Jogador B', price: 0.25, pool: 25000 },
      { id: '3', name: 'Jogador C', price: 0.20, pool: 20000 },
      { id: '4', name: 'Outro', price: 0.25, pool: 25000 }
    ],
    tags: ['Desporto', 'Futebol', 'Angola'],
  },
  {
    id: 'm9',
    question: 'Qual região terá maior impacto económico este mês?',
    category: 'Geopolítica',
    image_url: 'https://picsum.photos/seed/geopolitics/400/200',
    volume: 1300000,
    end_date: '2026-03-31T23:59:59Z',
    yes_price: 0,
    no_price: 0,
    pool_yes: 0,
    pool_no: 0,
    is_multi: true,
    outcomes: [
      { id: '1', name: 'EUA', price: 0.34, pool: 34000 },
      { id: '2', name: 'Europa', price: 0.28, pool: 28000 },
      { id: '3', name: 'China', price: 0.26, pool: 26000 },
      { id: '4', name: 'África', price: 0.12, pool: 12000 }
    ],
    tags: ['Geopolítica', 'Economia', 'Global'],
  },
  {
    id: 'm10',
    question: 'Qual empresa liderará a IA em 2026?',
    category: 'Tech',
    image_url: 'https://picsum.photos/seed/ai-leader/400/200',
    volume: 2000000,
    end_date: '2026-12-31T23:59:59Z',
    yes_price: 0,
    no_price: 0,
    pool_yes: 0,
    pool_no: 0,
    is_multi: true,
    outcomes: [
      { id: '1', name: 'Google', price: 0.30, pool: 30000 },
      { id: '2', name: 'OpenAI', price: 0.35, pool: 35000 },
      { id: '3', name: 'Microsoft', price: 0.25, pool: 25000 },
      { id: '4', name: 'Outra', price: 0.10, pool: 10000 }
    ],
    tags: ['Tech', 'IA', 'Futuro'],
  },
  {
    id: 'm11',
    question: 'Como será o clima em Luanda este mês?',
    category: 'Clima',
    image_url: 'https://picsum.photos/seed/luanda-weather/400/200',
    volume: 400000,
    end_date: '2026-03-31T23:59:59Z',
    yes_price: 0,
    no_price: 0,
    pool_yes: 0,
    pool_no: 0,
    is_multi: true,
    outcomes: [
      { id: '1', name: 'Muito quente', price: 0.38, pool: 38000 },
      { id: '2', name: 'Normal', price: 0.42, pool: 42000 },
      { id: '3', name: 'Chuvoso', price: 0.20, pool: 20000 }
    ],
    tags: ['Clima', 'Luanda', 'Angola'],
  },
  {
    id: 'm12',
    question: 'Quem vencerá a próxima eleição?',
    category: 'Eleições',
    image_url: 'https://picsum.photos/seed/election-winner/400/200',
    volume: 3000000,
    end_date: '2027-08-31T23:59:59Z',
    yes_price: 0,
    no_price: 0,
    pool_yes: 0,
    pool_no: 0,
    is_multi: true,
    outcomes: [
      { id: '1', name: 'Partido A', price: 0.45, pool: 45000 },
      { id: '2', name: 'Partido B', price: 0.38, pool: 38000 },
      { id: '3', name: 'Outro', price: 0.17, pool: 17000 }
    ],
    tags: ['Eleições', 'Política', 'Angola'],
  },
];

export const MOCK_POSTS = [
  {
    id: '1',
    title: 'O Futuro da Economia Angolana em 2026',
    content: 'Especialistas prevêem um crescimento moderado do PIB angolano impulsionado pela diversificação económica e novos investimentos no sector agrícola.',
    category: 'Economia',
    image_url: 'https://picsum.photos/seed/economy-post/800/400',
    created_at: new Date().toISOString(),
    status: 'published'
  },
  {
    id: '2',
    title: 'Novas Tecnologias no Sector Petrolífero',
    content: 'A Sonangol anuncia a implementação de novas tecnologias de extracção que prometem aumentar a eficiência e reduzir o impacto ambiental.',
    category: 'Petróleo',
    image_url: 'https://picsum.photos/seed/oil-post/800/400',
    created_at: new Date().toISOString(),
    status: 'published'
  },
  {
    id: '3',
    title: 'Criptomoedas em Angola: O que esperar?',
    content: 'O debate sobre a regulação de activos digitais em Angola ganha força com a nova proposta do Banco Nacional de Angola.',
    category: 'Crypto',
    image_url: 'https://picsum.photos/seed/crypto-post/800/400',
    created_at: new Date().toISOString(),
    status: 'published'
  },
  {
    id: '4',
    title: 'Eleições 2027: Primeiras Sondagens',
    content: 'As primeiras sondagens indicam uma disputa renhida entre os principais partidos, com o foco na recuperação económica e justiça social.',
    category: 'Eleições',
    image_url: 'https://picsum.photos/seed/election-post/800/400',
    created_at: new Date().toISOString(),
    status: 'published'
  },
  {
    id: '5',
    title: 'Desporto Nacional: O Crescimento do Basquetebol',
    content: 'Angola continua a dominar o basquetebol africano, com novos talentos a surgirem nas academias locais e a despertarem interesse internacional.',
    category: 'Desporto',
    image_url: 'https://picsum.photos/seed/basketball-post/800/400',
    created_at: new Date().toISOString(),
    status: 'published'
  }
];
