import { Market } from './types';

export const CATEGORIES = [
  'Todos',
  'Trending',
  'Breaking',
  'Novo',
  'Angola',
  'Política',
  'Economia',
  'Petróleo',
  'Crypto',
  'Desporto',
  'Finanças',
  'Geopolítica',
  'Tech',
  'Cultura',
  'Clima',
  'Eleições',
];

export const MOCK_MARKETS: Market[] = [
  {
    id: '1',
    question: 'O Kwanza vai valorizar este mês?',
    category: 'Economia',
    imageUrl: 'https://picsum.photos/seed/kwanza/400/200',
    volume: 2000,
    endDate: '2026-04-01T23:59:59Z',
    yesPrice: 0.93,
    noPrice: 0.07,
    poolYes: 1860,
    poolNo: 140,
    tags: ['Angola', 'Kwanza', 'Economia'],
  },
  {
    id: '2',
    question: 'Euro ultrapassa 1050 KZ?',
    category: 'Economia',
    imageUrl: 'https://picsum.photos/seed/euro/400/200',
    volume: 1500,
    endDate: '2026-04-16T23:59:59Z',
    yesPrice: 0.50,
    noPrice: 0.50,
    poolYes: 750,
    poolNo: 750,
    resolved: true,
    resolutionOutcome: 'Yes',
    tags: ['Euro', 'Kwanza', 'Câmbio'],
  },
  {
    id: '3',
    question: 'Dólar ultrapassa 950 KZ?',
    category: 'Finanças',
    imageUrl: 'https://picsum.photos/seed/dollar/400/200',
    volume: 3000,
    endDate: '2026-01-07T23:59:59Z',
    yesPrice: 0.50,
    noPrice: 0.50,
    poolYes: 1500,
    poolNo: 1500,
    tags: ['Dólar', 'Kwanza', 'Finanças'],
  },
  {
    id: '4',
    question: 'Real ultrapassa 160 KZ?',
    category: 'Finanças',
    imageUrl: 'https://picsum.photos/seed/real/400/200',
    volume: 800,
    endDate: '2026-05-31T23:59:59Z',
    yesPrice: 0.50,
    noPrice: 0.50,
    poolYes: 400,
    poolNo: 400,
    tags: ['Real', 'Kwanza', 'Finanças'],
  },
];
